# Generated by Django 2.2.5 on 2020-09-22 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memeocr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocrimage',
            name='editimage',
        ),
    ]
